= Miscellaneous Notes
:page-tags: go cmdline tips
:favicon: https://fernandobasso.dev/cmdline.png
:icons: font
:sectlinks:
:sectnums!:
:toclevels: 6
:toc: left
:source-highlighter: highlight.js
:stem: latexmath
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Intro

This file contains some commands or other things that I have found important to job down for quick lookup.

== Foundations

To run a project containing a `main.go` file with a `main()` function in the current directory:

[source,bash]
----
$ go run .
----

`go run` also accepts individual files, directories or packge names:

[source,bash]
----
$ go run ./main.go
$ go run ./libs/rand/
$ go run ./mypkg.example.org
----

=== ServerMux

ServerMux treads route pattern “/” as _catch all_ wildcard.

A host like ":4000" means all inter faces on the server machine, on port 400.
It is possible to use _named ports_ like ":http" or ":http-alt", in which case `http.ListenAndServe()` will attempt to use `/etc/services` to determine the port numbers.

=== ServerMux trailing forward slashes

A pattern like `/foo/view` (no trailing slash) matches exactly "/foo/view".

A pattern like `/foo/view/` (with a trailing slash), which is known as a _subtree path pattern_, matches paths _starting_ with `/foo/view`, like if it was like `/foo/view/**`.
It explains why `/` is a _catch all_ pattern.
