= Miscellaneous Notes
:page-tags: go cmdline tips
:favicon: https://fernandobasso.dev/cmdline.png
:icons: font
:sectlinks:
:sectnums!:
:toclevels: 6
:toc: left
:source-highlighter: highlight.js
:stem: latexmath
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Intro

This file contains some commands or other things that I have found important to job down for quick lookup.

== Foundations

To run a project containing a `main.go` file with a `main()` function in the current directory:

[source,bash]
----
$ go run .
----

`go run` also accepts individual files, directories or packge names:

[source,bash]
----
$ go run ./main.go
$ go run ./libs/rand/
$ go run ./mypkg.example.org
----

=== ServerMux

ServerMux treads route pattern “/” as _catch all_ wildcard.

A host like ":4000" means all inter faces on the server machine, on port 400.
It is possible to use _named ports_ like ":http" or ":http-alt", in which case `http.ListenAndServe()` will attempt to use `/etc/services` to determine the port numbers.

=== ServerMux trailing forward slashes

A pattern like `/foo/view` (no trailing slash) matches exactly "/foo/view".

A pattern like `/foo/view/` (with a trailing slash), which is known as a _subtree path pattern_, matches paths _starting_ with `/foo/view`, like if it was like `/foo/view/**`.
It explains why `/` is a _catch all_ pattern.

To prevent `/` for being treated as a catch-all glob, add `{$}` after it:

`"/{$}"`:: Strictly match only the "/" root path (a single “/” followed by nothing else).
`"/foo/view/{$}"`:: Strictly match "/foo/view/ (ending with the “/”, followed by nothing else).

It means a route pattern like `"/foo/view/{$}"` will require the request URL to be "https://example.org/foo/view/", including the trailing slash), else it will not match.

Using `{$}` is only valid after the `/`, as route patterns that do not end with the slash are strict by definition.

== Routing

Create a serve mux:

[source,go]
----
mux := http.NewServeMux()
----

From `mux`, we can use either `Handle()` or `HandleFunc()`.
`Handle(handler)` takes a parameter that satisfies the `http.Handler` interface.

=== HandleFunc() example

This is the signature of `HandleFunc()`:

[source,go]
----
HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
----

And with that piece of information in mind, we could craft a simple example like
this one:

[source,go]
----
func (app *application) check(w http.ResponseWriter, _ *http.Request) {
	w.Write([]byte("It works! They said I was crazy but it works!!"))
}


mux := http.NewServeMux()
mux.HandleFunc("GET /check", handlerFn)
----

=== HandleFunc() and alice middleware chaining

Here we use `mux.HandleFunc()` because our handlers are actually methods.

[source,go]
----
package main

import (
	"net/http"

	"github.com/justinas/alice"
)

func (app *application) routes() http.Handler {
	mux := http.NewServeMux()

	fileServer := http.FileServer(http.Dir("./ui/static"))
	mux.Handle("GET /static/", http.StripPrefix("/static", fileServer))

	mux.HandleFunc("GET /{$}", app.home)
	mux.HandleFunc("GET /snippet/view/{id}", app.snippetView)
	mux.HandleFunc("GET /snippet/create", app.snippetCreate)
	mux.HandleFunc("POST /snippet/create", app.snippetCreatePost)

	// A standard middleware chain which is intended to be applied to every
	// request the application receives.
	standard := alice.New(app.recoverPanic, app.logRequest, commonHeaders)

	return standard.Then(mux)
}
----

=== With session storage middleware

We use `mux.Handle()` instead of `mux.HandleFunc()` because `alice.ThenFunc()` method returns an `http.Handler` rather than `http.HandlerFunc`.

[source,go]
----
func (app *application) routes() http.Handler {
	mux := http.NewServeMux()

	fileServer := http.FileServer(http.Dir("./ui/static"))
	mux.Handle("GET /static/", http.StripPrefix("/static", fileServer))

	// A new middleware specific for the dynamic routes.
	dynamic := alice.New(app.sessMgr.LoadAndSave)

	mux.Handle("GET /{$}", dynamic.ThenFunc(app.home))
	mux.Handle("GET /snippet/view/{id}", dynamic.ThenFunc(app.snippetView))
	mux.Handle("GET /snippet/create", dynamic.ThenFunc(app.snippetCreate))
	mux.Handle("POST /snippet/create", dynamic.ThenFunc(app.snippetCreatePost))

	// A standard middleware chain which is intended to be applied to every
	// request the application receives.
	standard := alice.New(app.recoverPanic, app.logRequest, commonHeaders)

	return standard.Then(mux)
}
----