= Snippet Box (from the book Let's Go)
:page-tags: go snippet web app api
:favicon: https://fernandobasso.dev/cmdline.png
:icons: font
:sectlinks:
:sectnums!:
:toclevels: 6
:toc: left
:source-highlighter: highlight.js
:stem: latexmath
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Intro

Started the project with go 1.23.1.

== Run the web application

=== Transport Layer Security

Generate a dev-only TLS certificate as it is required to run our application:

[source,go]
----
$ mkdir -v ./tls
$ cd ./tls

$ find "$GOROOT" -iname '*generate_cert*'
/home/deveng/.goenv/versions/1.24.0/src/crypto/tls/generate_cert.go

$ go run "$GOROOT/src/crypto/tls/generate_cert.go" \
    --rsa-bits=2048 \
    --host=localhost
2025/02/25 10:14:17 wrote cert.pem
2025/02/25 10:14:17 wrote key.pem
----

[NOTE]
====
The browser will complain about an _untrusted_ certificate the first time the application is accessed
That is fine as we know we are using a local, dev-only certificate that has not been trusted but an authority.
The good thing is that we _can_ now run our application in local using a secure connection (HTTPS).
====

=== DB auth env vars

Providing the database authentication details is necessary.
This is currently done through the shell's environment variables:

[source,bash]
----
$ PG_HOST=localhost \
    PG_USER=user \
    PG_PASS=pass \
    PG_DBNAME=dbname \
    go run ./cmd/web \
    -addr=':4000'
----

Or with gow:

[source,bash]
----
$ PG_HOST=localhost \
    PG_USER=user \
    PG_PASS=pass \
    PG_DBNAME=dbname \
    $GOPATH/bin/gow -e=go,html run ./cmd/web \
    -addr=':4000'
----

== PostgreSQL database

The PostgreSQL database is provided through docker.
Start it with these commands:

[source,bash]
----
$ cd ./docker
$ docker compose up
----

On another shell session, connect to the database:

[source,bash]
----
$ docker exec -it pgsnipbox psql -U dev -d snipbox_dev
----